spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: biubiu123
    url: jdbc:mysql://36.134.145.235:3306/guli_sms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: guli-coupon
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #配置全局主键自增
server:
  port: 7000
