spring:
  cloud:
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu

        - id: product_route
          uri: lb://guli-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #如果将product放在admin后，会被admin先拦截，故product尧放在高优先级上

        - id: third_route
          uri: lb://guli-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://guli-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://guli-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api?(?<segment>.*),/renren-fast/$\{segment}
          #lb:负载均衡
          #前端请求都带上api
          #由于renrenfast项目的请求路径必须是localhost:88/renrenfast/yanzhengma.jpg
          #而原始访问路径localhost:88/api/yanzhengma.jpg
          #filters会重写请求,将api换成renren-fast




